spring:
  datasource:
    url: jdbc:postgresql://imageuploader.c8p3xhjtds99.us-east-1.rds.amazonaws.com:5432/imageuploader
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
aws:
  region: eu-west-2
  s3:
    buckets:
      name: nerd-image-uploader-123
server:
  port: 3000


